export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const ADD_REGISTRANT = 'ADD_REGISTRANT';
export const GET_EVENT_REGISTRANTS = 'GET_EVENT_REGISTRANTS';
export const TOGGLE_RESULT_DIALOG = 'TOGGLE_RESULT_DIALOG';
export const SIGN_IN_REGISTRANT = 'SIGN_IN_REGISTRANT';